version: "3"
services:
    php82:
        container_name: php82
        build:
            context: ./
            dockerfile: ./php82/Dockerfile
        restart: always
        ports:
            - "82:80"
        volumes:
            - ${CONFIG_APACHE}
            - ${PUBLIC_HTML}
            - ./php82/php.ini:/usr/local/etc/php/php.ini:z
        depends_on:
            - mariadb
    php81:
        container_name: php81
        build:
            context: ./
            dockerfile: ./php81/Dockerfile
        restart: always
        ports:
            - "81:80"
        volumes:
            - ${CONFIG_APACHE}
            - ${PUBLIC_HTML}
            - ./php81/php.ini:/usr/local/etc/php/php.ini:z
        depends_on:
            - mariadb
    php73:
        container_name: php73
        build:
            context: ./
            dockerfile: ./php73/Dockerfile
        restart: always
        ports:
            - "73:80"
        volumes:
            - ${CONFIG_APACHE}
            - ${PUBLIC_HTML}
            - ./php73/php.ini:/usr/local/etc/php/php.ini:z
        depends_on:
            - mariadb
    php72:
        container_name: php72
        build:
            context: ./
            dockerfile: ./php72/Dockerfile
        restart: always
        ports:
            - "72:80"
        volumes:
            - ${CONFIG_APACHE}
            - ${PUBLIC_HTML}
            - ./php72/php.ini:/usr/local/etc/php/php.ini:z
        depends_on:
            - mariadb
    php56:
        container_name: php56
        build:
            context: ./
            dockerfile: ./php56/Dockerfile
        restart: always
        ports:
            - "56:80"
        volumes:
            - ${CONFIG_APACHE}
            - ${PUBLIC_HTML}
            - ./php56/php.ini:/usr/local/etc/php/php.ini:z
        depends_on:
            - mariadb
    mariadb:
        container_name: db
        image: mariadb:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./mysql/data/:/var/lib/mysql:z
